### ISSUE TITLE
Text inside documents not indexed

### ISSUE THREAD

**Issue by bagatel** [opensemanticsearch/solr-php-ui#3]
Hi,

I have been installing the server on a Ubuntu box, was easy and running fast, thanks a lot for this. After indexing almost 1.300.000 documents search remained fast!

However I noticed that while I could make a search on words that were part of the file name, the text inside the document themselves (PDF for example) were not available for search.

I get this on the log:

> Indexing new file: /XXXXX/docbookxsl_4_duplex.2.pdf
> Exception while data enrichment with plugin enhance_extract_text_tika_server:
> Exception while data enrichment with plugin enhance_pdf_ocr: content_type
> Indexing new file: /XXXXX/Charte Guide Styles OCDE.pdf
> Exception while data enrichment with plugin enhance_extract_text_tika_server:
> Exception while data enrichment with plugin enhance_pdf_ocr: content_type

I don't know if that's relevant, nor how to fix. 
I get results for searching for "Styles" but not for "lexicales" which is a word inside "Charte Guide Styles OCDE.pdf"

Note: the PDF are not images, so no OCR needed.

Thanks for your help.

**Comment by opensemanticsearch** [comment]
Tika is the service which extracts the text of the files.

If you use the Open Semantic ETL (Extract Transfer Load) standalone with an existing Solr or Elastic Search installation (not installed the full Open Semantic Search Server package which includes Tika & Solr) you need to setup a Tika Server.

For that case there are preconfigured Debian & Ubuntu packages available for download at the Open Semantic Search website.

Next week there will be a new release based on newer Apache Tika release.
