### ISSUE TITLE
More buttons for snippets

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#36]
After https://github.com/opensemanticsearch/solr-php-ui/pull/35 missing the more button for entities under the snippets and more button for snippets doesn't work.

To check before new release.

**Comment by opensemanticsearch** [comment]
More button for snippets seems minor issue, only different or missing class names like phps more_id after "more-snips" in html code.

Maybe similar in php variable names for more entities.

**Comment by Mandalka** [comment]
With https://github.com/opensemanticsearch/solr-php-ui/commit/d59c19e6221fdbe6ab392c1892b12aba88872053 button for more snippets works again after adding more id to new styled html elements.

**Comment by Mandalka** [comment]
With https://github.com/opensemanticsearch/solr-php-ui/commit/d41d71111169cd3a6b9f94f0a97237931fa0fd65 more entities are shown on click on button "more", too.
