### ISSUE TITLE
Preview: Show annotations in additional tab "Tags and annotations"

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#42]
In preview show annotations from Hypothesis and from Semantic Tagger in additional tab "Tags and Annotations", not only in tab "Meta".

**Comment by Mandalka** [comment]
![annotations](https://user-images.githubusercontent.com/1010780/37090284-047b82de-2204-11e8-8050-0aaa091124f5.png)
