### ISSUE TITLE
Map view by leaflet

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#45]
Integrate [leaflet.js](http://leafletjs.com/) to see search results including geo coordinates on an [Openstreetmap](https://www.openstreetmap.org) map

**Comment by Mandalka** [comment]
Documents with Geodata in the facet location_wkt_ss are shown now in the new view/tab map by view.map.php ...
![map](https://user-images.githubusercontent.com/1010780/37525002-df074248-292b-11e8-9d3e-9111f974b0a4.png)
