### ISSUE TITLE
Link to "Preview" in list with small previews of images goes to old previewer

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#47]
Change linkt to preview.php to new rich preview by index like in normal result lists.

**Comment by Mandalka** [comment]
Same for video view.

**Comment by Mandalka** [comment]
Changed preview link to new rich preview for image view.

**Comment by Mandalka** [comment]
(Re)Moved multiple/same command templates from multiple views to new reused view.commands.php, so its changed for video view and all other views, too.
