### ISSUE TITLE
Change value separator of taxonomy facets in filter URL parameters

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#60]
To be able to use URIs or RDF/SKOS labels with / in their label in taxonomy facets, change the default separator for values/paths in filter URL options of taxonomy facets (but let it for filepath facet)

**Comment by Mandalka** [comment]
Changed separator of taxonomy values from / to tab so URIs with / or RDF/SKOS labels with / can be used as labels, so only file path uses / as separator.

Optimized parameter values (a/b/c, so in multivalued taxonomies not full taxonomy per child/value in filter HTTP parameter like before (a/ab/abc).
