### ISSUE TITLE
Move Tika processing metadata fields to tab ETL instead of Metadata

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#64]
Move Tika processing metadata fields / values like 
X-Parsed-By:
    org.apache.tika.parser.DefaultParser
    org.apache.tika.parser.mp4.MP4Parser

X-TIKA_content_handler:
ToTextContentHandler

X-TIKA_parse_time_millis:
283

From tab Metadata to tab ETL.

**Comment by Mandalka** [comment]
Moved Tika processing status fields X-Parsed-By_ss and X-TIKA_* from Preview tab "Metadata" to tab "Import & analysis process (ETL)" by https://github.com/opensemanticsearch/solr-php-ui/commit/d5244c30367da0e6109175fa789dc8a32cc44114
