### ISSUE TITLE
Read Solr host config from environment variable if set

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#68]
Read Solr host config from environment variable if set so configurable by environment variable, so we can configure them dynamic in/by [Docker](https://github.com/opensemanticsearch/open-semantic-search/issues/104) config without modifications of config files in containers.

**Comment by Mandalka** [comment]
Implemented environment variable SOLR_PHP_UI_SOLR_HOST
