### ISSUE TITLE
Visual graph view: Choose facets/properties

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#7]
Add UI element for choice of relevant facets/fields/properties for connections to disable visualization of (many) irrelevant connections/coocurences

**Comment by opensemanticsearch** [comment]
Since thanks to a client now we have [controls for count of facet values](https://github.com/opensemanticsearch/open-semantic-search/issues/38), use such parameters like [facet/properties controls](https://github.com/opensemanticsearch/solr-php-ui/issues/7) for graph analysis view, too.

**Comment by Mandalka** [comment]
Graph visualization is now done by [Django app Open Semantic Visual Linked Data Graph Explorer](https://github.com/opensemanticsearch/open-semantic-visual-graph-explorer) based on Cytoscape.js.

The Solr-PHP-UI graph view has now user interfaces for parametrize the graph analysis and graph visualization by selection of entity types / classes / facets / properties.
