### ISSUE TITLE
UI for parameters of graph / network visualization

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#8]
User interfaces for graph visualization parameters.

Maybe do graph visualization part by Django App or API or Javascript App instead of PHP

**Comment by opensemanticsearch** [comment]
Since thanks to a client now we have [controls for count of facet values](https://github.com/opensemanticsearch/open-semantic-search/issues/38), use such parameters like [facet/properties controls](https://github.com/opensemanticsearch/solr-php-ui/issues/7) for graph analysis view, too.

**Comment by Mandalka** [comment]
Graph visualization is now done by [Django app Open Semantic Visual Linked Data Graph Explorer](https://github.com/opensemanticsearch/open-semantic-visual-graph-explorer) based on Cytoscape.js.

The Solr-PHP-UI graph view has now user interfaces for parametrize it like setup of entity types / classes and amount of initial entities.
